name: Build and Deploy to Railway
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  push:
    branches:
      - master
env:
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TELEGRAM_BOT_GOLANG_TOKEN }}
  RAILWAY_PROJECT: 45383c9d-1964-4869-a084-05c435388dc9
  RAILWAY_ENVIRONMENT: production
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Railway CLI
        run: curl -sL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | sh

      - name: Deploy to Railway
        run: railway up
