name: Build and Deploy to Railway
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  push:
    branches:
      - master
env:
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TELEGRAM_BOT_GOLANG_TOKEN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Install Railway CLI
        run: curl -sL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | sh

      - name: Deploy to Railway
        run: railway deploy --project 45383c9d-1964-4869-a084-05c435388dc9 --environment production --token ${{ secrets.RAILWAY_TELEGRAM_BOT_GOLANG_TOKEN }}
